import type { Template } from '@/types';

/** 内置模板 */
export const builtinTemplates: Template[] = [
  {
    id: 'classic',
    name: '简约经典',
    description: '黑色圆角方块 + 纯白背景，经典百搭',
    preview: '',
    params: {
      dot: {
        style: 'rounded',
        cornerRadius: 12,
        circleRatio: 0.85,
        sizeRatio: 0.9,
      },
      color: {
        foreground: '#000000',
        background: '#FFFFFF',
        gradientType: 'none',
        gradientDirection: 'diagonal',
        gradientColor1: '#000000',
        gradientColor2: '#333333',
      },
      border: {
        style: 'none',
        width: 8,
        color: '#000000',
        borderRadius: 16,
        labelText: '',
        labelColor: '#000000',
        labelFontSize: 14,
      },
    },
  },
  {
    id: 'business',
    name: '商务深蓝',
    description: '深蓝渐变前景 + 圆形码点 + 细边框',
    preview: '',
    params: {
      dot: {
        style: 'circle',
        cornerRadius: 12,
        circleRatio: 0.85,
        sizeRatio: 0.88,
      },
      color: {
        foreground: '#1a365d',
        background: '#FFFFFF',
        gradientType: 'linear',
        gradientDirection: 'vertical',
        gradientColor1: '#1a365d',
        gradientColor2: '#2b6cb0',
      },
      border: {
        style: 'solid',
        width: 4,
        color: '#2b6cb0',
        borderRadius: 8,
        labelText: '',
        labelColor: '#000000',
        labelFontSize: 14,
      },
    },
  },
  {
    id: 'vibrant',
    name: '活力渐变',
    description: '橙到粉对角线渐变 + 圆角方块',
    preview: '',
    params: {
      dot: {
        style: 'rounded',
        cornerRadius: 14,
        circleRatio: 0.85,
        sizeRatio: 0.92,
      },
      color: {
        foreground: '#ed8936',
        background: '#FFFFFF',
        gradientType: 'linear',
        gradientDirection: 'diagonal',
        gradientColor1: '#ed8936',
        gradientColor2: '#e53e3e',
      },
      border: {
        style: 'none',
        width: 8,
        color: '#000000',
        borderRadius: 16,
        labelText: '',
        labelColor: '#000000',
        labelFontSize: 14,
      },
    },
  },
  {
    id: 'fresh',
    name: '清新绿意',
    description: '绿色圆形码点 + 纯白底，清新自然',
    preview: '',
    params: {
      dot: {
        style: 'circle',
        cornerRadius: 12,
        circleRatio: 0.8,
        sizeRatio: 0.85,
      },
      color: {
        foreground: '#38a169',
        background: '#FFFFFF',
        gradientType: 'none',
        gradientDirection: 'diagonal',
        gradientColor1: '#000000',
        gradientColor2: '#333333',
      },
      border: {
        style: 'none',
        width: 8,
        color: '#000000',
        borderRadius: 16,
        labelText: '',
        labelColor: '#000000',
        labelFontSize: 14,
      },
    },
  },
  {
    id: 'dark',
    name: '暗夜模式',
    description: '白色码点 + 深灰背景 + 方形码点',
    preview: '',
    params: {
      dot: {
        style: 'square',
        cornerRadius: 12,
        circleRatio: 0.85,
        sizeRatio: 0.95,
      },
      color: {
        foreground: '#FFFFFF',
        background: '#1a1a2e',
        gradientType: 'none',
        gradientDirection: 'diagonal',
        gradientColor1: '#000000',
        gradientColor2: '#333333',
      },
      border: {
        style: 'none',
        width: 8,
        color: '#000000',
        borderRadius: 16,
        labelText: '',
        labelColor: '#000000',
        labelFontSize: 14,
      },
    },
  },
  {
    id: 'geek',
    name: '极客像素',
    description: '纯方块 + 霓虹绿前景 + 深黑底',
    preview: '',
    params: {
      dot: {
        style: 'square',
        cornerRadius: 0,
        circleRatio: 0.85,
        sizeRatio: 1,
      },
      color: {
        foreground: '#39ff14',
        background: '#0a0a0a',
        gradientType: 'none',
        gradientDirection: 'diagonal',
        gradientColor1: '#000000',
        gradientColor2: '#333333',
      },
      border: {
        style: 'solid',
        width: 2,
        color: '#39ff14',
        borderRadius: 0,
        labelText: '',
        labelColor: '#000000',
        labelFontSize: 14,
      },
    },
  },
];
